version: '3.8'
services:
  ghost:
    image: ghost:1-alpine
    restart: always
    environment:
      - database__client=mysql
      - database__connection__host=mysql
      - database__connection__user=root
      - database__connection__password=root_password
      - database__connection__database=ghost
    depends_on:
      - mysql
    ports:
      - 2368:2368
    volumes:
      - ghost-data:/var/lib/ghost/content

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ghost

volumes:
  ghost-data:
